import "./globals.css";
import type { Metadata } from "next";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import GlobalCssPriority from "./GlobalCssProirity";
import { CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Neighborhood Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="root">
        <CssBaseline />
        <GlobalCssPriority>{children}</GlobalCssPriority>
      </body>
    </html>
  );
}
